"""integrando o banco de dados aos endpoints e reescrevendos os testes

Revision ID: 2fb2b15a52ee
Revises: 3b900fe85ded
Create Date: 2026-07-22 14:33:35.681158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb2b15a52ee'
down_revision: Union[str, Sequence[str], None] = '3b900fe85ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
